export const routes = {
  home: '/',
  about: '/about',
  activities: '/activities',
  gallery: '/gallery',
  getInvolved: '/get-involved',
  donate: '/donate',
  contact: '/contact',
  dashboard: '/dashboard',
  dashboardOverview: '/dashboard',
  dashboardDonations: '/dashboard/donations',
  dashboardVolunteers: '/dashboard/volunteers',
  dashboardActivities: '/dashboard/activities',
  dashboardGallery: '/dashboard/gallery',
  dashboardSettings: '/dashboard/settings',
  login: '/login',
  register: '/register',
  privacy: '/privacy',
  terms: '/terms',
  notFound: '*',
}